name: CI

on:
  workflow_run:
    workflows: ["ci"]
    branches: [ master ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
      - uses: actions/checkout@v2

        # Creates dist folder
        - run: mkdir www
        - run: cp -R ./dist/ ./www/
        - run: cp -R ./examples/ ./www/
        
        # Deploy to github pages
        - name: Deploy to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@v4.2.5
          with:
            branch: gh-pages
            folder: www